apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "graphile-migrate.fullname" . }}-{{ .Values.image.tag }}
  labels:
    {{- include "graphile-migrate.labels" . | nindent 4 }}
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["yarn", "workspace", "database", "mig", "run", "migrations/scripts/afterReset.sql"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialSecrets.root }}
                  key: databaseURI
            - name: DATABASE_AUTHENTICATOR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialSecrets.authenticator }}
                  key: username
            - name: DATABASE_VISITOR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialSecrets.visitor }}
                  key: username
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: [ "yarn", "workspace", "database" , "graphile-migrate", "migrate" ]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialSecrets.owner }}
                  key: databaseURI
            - name: DATABASE_AUTHENTICATOR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialSecrets.authenticator }}
                  key: username
            - name: DATABASE_VISITOR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialSecrets.visitor }}
                  key: username
      restartPolicy: Never
