image:
  repository: registry.gitlab.com/ncrmro/postgres-graphql/migrations
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

migrationCommand: [ "yarn", "workspace", "database" , "graphile-migrate", "migrate" ]

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

databaseURISecret: postgres-database-owner-url-credentials

credentialSecrets:
  root: postgres-root-credentials
  owner: postgres-owner-credentials
  authenticator: postgres-authenticator-credentials
  visitor: postgres-visitor-credentials

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
