apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "postgres-graphql.fullname" . }}-secrets
data:
  jwtKey: {{ required "A valid .Values.jwtKey entry required!" .Values.jwtKey | b64enc | quote }}
