apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.fullname" . }}-app-config
  namespace: {{ .Release.Namespace }}
data:
  app-config.yaml: |-
{{ toYaml .Values.appConfig | indent 4 }}
