apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-root-credentials
data:
  postgresql-password: {{ .Values.postgresqlPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-owner-credentials
data:
  username: {{ .Values.database.owner.username | b64enc | quote }}
  password: {{ .Values.database.owner.password | b64enc | quote }}
  databaseURI: {{ include "postgres.owner.databaseURI" . | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-authenticator-credentials
data:
  username: {{ .Values.database.authenticator.username | b64enc | quote }}
  password: {{ .Values.database.authenticator.password | b64enc | quote }}
  databaseURI: {{ include "postgres.authenticator.databaseURI" . | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-visitor-credentials
data:
  username: {{ .Values.database.visitor.username | b64enc | quote }}
