name: Lint
on: ['push']

jobs:
  lint-test:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.0.1

    - name: Add Chart Repos
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Run chart-testing (lint)
      run: ct lint --all
