name: Lint
on: ['push']
#  push:
#    paths:
#    - 'charts/**'

jobs:
  release-charts:
    runs-on: 'ubuntu-latest'
    needs: lint-test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hello World
      run: echo "Hello world!"
#    - uses: "marvinpinto/action-automatic-releases@latest"
#      with:
#        repo_token: "${{ secrets.GITHUB_TOKEN }}"
#        automatic_release_tag: "latest"
#        prerelease: false
#        title: "Development Build"
#        files: |
#          LICENSE.txt
#          *.jar
